[package]
name = "webscraper_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.8" 
reqwest = {version = "0.12.5", features = ["json"]}
serde_json = "1.0.120"
tokio = {version = "1.38.0", features = ["full"]}

